include:
  - project: templates/gitlab-ci
    ref: "master"
    file: java-build-publish.yaml

variables:
  ENABLE_CHECK: "true"

test:
  artifacts:
    paths:
      - "**/build/kover-reports/result.xml"
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"

convert-coverage-report:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: test
  image: registry.gitlab.com/haynes/jacoco2cobertura:latest
  rules:
    - if: $ENABLE_CHECK == "true" && $CI_COMMIT_TAG == null
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py lib/build/kover-reports/result.xml $CI_PROJECT_DIR/lib/src/main/kotlin/ > cobertura.xml
  needs:
    - job: test
      artifacts: true
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
