include:
  - project: templates/gitlab-ci
    ref: "master"
    file: java-build-publish.yaml
  - project: templates/gitlab-ci
    ref: "master"
    file: container-image.yaml

variables:
  ENABLE_CHECK: "true"

test:
  artifacts:
    paths:
      - "**/build/kover-reports/result.xml"
    reports:
      junit:
        - "**/build/test-results/test/TEST-*.xml"

container:
  stage: publish
  only:
    - tags
  extends: .build_with_kaniko
