include:
  - project: templates/gitlab-ci
    ref: "master"
    file: java-build-publish.yaml

variables:
  ENABLE_CHECK: "true"

check:
  artifacts:
    paths:
      - build/kover-reports/result.xml
    reports:
      junit:
        - build/test-results/test/TEST-*.xml

convert-coverage-report:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: check
  image: registry.gitlab.com/haynes/jacoco2cobertura:latest
  rules:
    - if: $ENABLE_CHECK == "true" && $CI_COMMIT_TAG == null
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py build/kover-reports/result.xml $CI_PROJECT_DIR/src/main/kotlin/ > build/kover-reports/cobertura.xml
  needs:
    - job: check
      artifacts: true
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/kover-reports/cobertura.xml
